spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/spring_batch?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true #rewriter~: bulk Insert를 사용하기 위한 옵션
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root

  jpa:
    hibernate:
      ddl-auto: update

batch:
  initialize-schema: never